app/(pages)/(content)/profile/page.tsx

Este PR soluciona un problema en la obtención de las publicaciones y la descripción del usuario. Anteriormente, el sistema solo estaba obteniendo las publicaciones y la descripción de un usuario específico (con ID "7"), independientemente del usuario autenticado. Ahora, se realiza correctamente una solicitud de las publicaciones, la descripción y las mascotas asociadas al usuario actualmente autenticado.
**Ticket del Jira**
[S-212](https://projectliderfiuni2025.atlassian.net/browse/SCRUM-212)
- Se ajustó la lógica para obtener las publicaciones del usuario basado en el userId del usuario almacenado en localStorage, en lugar de usar un ID fijo.
- Se maneja correctamente la validación de la existencia del userId y se garantiza que los datos obtenidos sean consistentes.
1. Iniciar sesión en …

Fix: Get posts and user description by ID obtained from localStorage

---

app/(pages)/(content)/profile/page.tsx
app/(pages)/auth/layout.tsx
app/(pages)/auth/login/page.tsx
app/layout.tsx
app/loading.tsx
components/navbar.tsx
components/petCard/cardText.tsx
components/userHeader.tsx
contexts/authContext.tsx
package-lock.json
package.json
tailwind.config.ts
types/auth.ts
types/userProfile.ts
types/users.ts
utils/auth-client.ts
utils/errors/AuthError.ts

fix(auth): Solucionar múltiples errores de autenticación y mejorar UX
Corrige problemas en el contexto de autenticación, agrega componente de loading
para mejorar la experiencia de usuario durante procesos de autenticación y
corrige errores de tipo en la página de login.
Ticket [S-217](https://projectliderfiuni2025.atlassian.net/browse/SCRUM-217?atlOrigin=eyJpIjoiYTg0NzBjNzQ1YWYzNDViYzk2OTAzYWU3Mjk3MTVmMTUiLCJwIjoiaiJ9)

S-217 Fix Auth

---

app/not-found.tsx

Se agrego una pagina de Not Found 
[S-218](https://projectliderfiuni2025.atlassian.net/browse/SCRUM-218?atlOrigin=eyJpIjoiZjBkZTEzMDBhYzZjNGYwMzlhMzlmMThiZmM1MWY2NzkiLCJwIjoiaiJ9)

S-218   not found page

---

components/navbar.tsx

Resaltado en color del botón del navbar dependiendo de la sección en la que se encuentre

S226 - Resaltado en color del botón del navbar dependiendo de la sección en la que se encuentre

---

app/(pages)/(content)/dashboard/page.tsx
components/Section.tsx
types/post.ts
utils/pets.http.ts
utils/posts.http.ts

Actualice el dashboard para que reciba los post con llamadas a la api y el componente section para ser utilizado con filtros
**Link de ticket de Jira**
[S-224](https://projectliderfiuni2025.atlassian.net/browse/SCRUM-224)
> [!IMPORTANT]
> Se debe cambiar la logica de obtener postTypes, se discutira con el responsable del api en el backend
`  <Section title = 'Blog' postTypeId={3} path='blog' postType="blog" items={posts} loading = {loading} error = {error}</Section>
`

Update dashboard to connect to backend

---

app/(pages)/(content)/adoption/page.tsx
app/(pages)/(content)/dashboard/page.tsx
app/(pages)/(content)/profile/page.tsx
components/buttons/edit-button.tsx
components/petCard/pet-card.tsx
components/profile/detail-form.tsx
components/section.tsx
components/title.tsx

Este PR permite a un usuario editar datos de su perfil de forma estática
Este PR soluciona un fix del S-212 #34 
> [!IMPORTANT]
> Este ticket aun no esta terminado, subo para que no aparezca mas el error de profile
- Conectar la logica de editar los datos del usuario a la api
Fix solucionado [S12](https://projectliderfiuni2025.atlassian.net/browse/SCRUM-212
)
- Se creó un componente Details 
- Se modifico Profile con nuevos botones
- Se arreglo un fix de profile que dio error despues de actualizar la api
- Se maneja la logica de editar userProfile
- Se refactorizó section para aceptar cualquier tipo de post o pet

S-187 Editar perfil de usuario - Estado (En progreso) 

---

app/(pages)/(content)/profile/favorites/page.tsx
types/favorites.ts
utils/favorites-posts.http.ts

Se creó la página para ver los favoritos utilizando la api de favoritos.
Como se usa:
- Ingresar a la cuenta sebasimeon01@gmail.com boludo01
- Escribir en la URL /profile/favorites
- Si ha entrado con la cuenta se debería ver un favorito

S195 favorites page

---

app/(pages)/(content)/administration/page.tsx
components/navbar-admin.tsx
components/navbar.tsx

Se creo la pagina de administracion con acceso a mascotas, razas y rstados de la mascota, por ahora. dichos accesos obtendran un a pagina 404 hasta que se implementen sus respectivas paginas.

Pagina de administracion

---

app/(pages)/(content)/profile/my-pets/[user-id]/page.tsx
app/(pages)/(content)/profile/my-posts/[user-id]/page.tsx
app/(pages)/(content)/profile/page.tsx
components/footer.tsx

Este PR implementa la pantalla de lista de publicaciones y de mascotas de un usuario, la cual es accesible desde el perfil del usuario. Además, se han agregado filtros estaticos  de acuerdo a la ciudad, tipo de mascota y edad.
- [FE - Realizar pantalla de lista de publicaciones de un usuario con acceso desde el perfil](https://projectliderfiuni2025.atlassian.net/browse/SCRUM-193)
- Se creó la página `MyPostsPage` para mostrar las publicaciones del usuario.
- Se creó la página `MyPetsPage` para mostrar las publicaciones del usuario.
- Se implementaron filtros estaticos.
- Se actualizó la lógica de ruteo en la página de perfil para redirigir a la pantalla de publicaciones.
- Se implementó la lógica de carga de datos de publicaciones desde la API.

FE - Realizar pantalla de lista de publicaciones de un usuario con acceso desde el perfil

---

app/(pages)/(content)/profile/page.tsx

Se agrego funcionalidad al boton contactar, se lo hizo desplegable con botones para correo y para contactar por WhatsApp.

Scrum 204 fe agregar boton de contacto

---

app/(pages)/auth/login/page.tsx
app/(pages)/auth/reset-password-request/page.tsx
app/(pages)/auth/reset-password/page.tsx
services/index.ts
services/request-password-service.ts

Se agrego pantalla funcional para solicitar contrasena nueva.

Scrum 183 fe form para cambio contrasena

---

app/(pages)/auth/reset-password/page.tsx
services/request-password-service.ts

Se completo el ciclo para poder realizar el cambio de contrasena.

Scrum 184 fe realizar form doble doble contrasena

---

components/navbar-admin.tsx
components/user-header.tsx

Se realizaron los cambios solicitados.

Fix administration page

---

app/(pages)/(content)/profile/page.tsx
app/validations/user-profile.ts
components/profile/detail-form.tsx
package.json
types/user-profile.ts
utils/user-profile-client.ts

Este PR permite a un usuario editar datos de su perfil haciendo llamadas a la api 
- Se creó un componente Details 
- Se modifico Profile con nuevos botones
- Se arreglo un fix de profile que dio error despues de actualizar la api
- Se maneja la logica de editar userProfile
- Se refactorizó section para aceptar cualquier tipo de post o pet

S 187 edit profile

---

app/(pages)/(content)/administration/card.tsx
app/(pages)/(content)/administration/configuration/form-animal.tsx
app/(pages)/(content)/administration/configuration/form-pet-status.tsx
app/(pages)/(content)/administration/configuration/page.tsx
components/admin-card/clickable-tag.tsx
components/confirm-modal.tsx
components/navbar-admin.tsx
types/animal.ts
types/pet-status.ts
utils/animals.http.ts
utils/pet-statuses.http.ts

Se creo componente card para listar los animales y estados de mascota, con las implementaciones de editar, crear y eliminar cada item
[ticket](https://projectliderfiuni2025.atlassian.net/browse/SCRUM-189?atlOrigin=eyJpIjoiNGI1MDFlOTQ0MWVjNDQwZmE1MjVkMjIzMmEzNjA5MWUiLCJwIjoiaiJ9)

Sc 199 fe realizar formulario para crear modificar y borrar animales y estado de mascota

---

app/(pages)/(content)/posts/[id]/page.tsx
components/banners.tsx
components/buttons/send-button.tsx
components/comments/comment-form.tsx
components/comments/comment-item.tsx
components/comments/comments.tsx
components/petCard/pet-card.tsx
components/post/post-buttons.tsx
components/post/post-comments.tsx
components/post/post-content.tsx
components/post/post-header.tsx
components/post/post-location-map.tsx
components/post/post-map.tsx
components/post/post-sidebar.tsx
components/ui/user-avatar.tsx
lib/comment-example.json
package-lock.json
package.json
types/comment.ts
utils/comments-client.ts
utils/posts.http.ts

…atar components; update banners and layout

S-250-Page-Post-Details

---

app/(pages)/(content)/administration/configuration/form-animal.tsx
app/(pages)/(content)/administration/configuration/form-pet-status.tsx

Se cambio el estilo del boton cancelar en los formularios para crear pet-status y animals

fix variant

---

app/(pages)/(content)/administration/report/[id]/page.tsx
app/(pages)/(content)/administration/report/page.tsx
app/(pages)/(content)/posts/[id]/page.tsx
components/administration/report/card-button.tsx
components/administration/report/report-list.tsx
components/navbar-admin.tsx
components/post/post-sidebar.tsx

Implementacion de la pagina de reportes en administracion

S 205 create reports

---

app/(pages)/(content)/about-us/page.tsx
app/(pages)/(content)/our-values/page.tsx
components/post/post-buttons.tsx

Pagina estatica con Vision, Mision y Valores.

Our values

---

app/(pages)/(content)/about-us/page.tsx
app/(pages)/(content)/dashboard/page.tsx
app/(pages)/(content)/layout.tsx
app/(pages)/(content)/missing/page.tsx
app/(pages)/(content)/our-values/page.tsx
app/(pages)/(content)/pets/[id]/page.tsx
app/(pages)/(content)/posts/[id]/page.tsx
app/(pages)/(content)/profile/favorites/page.tsx
app/(pages)/(content)/profile/my-pets/[user-id]/page.tsx
app/(pages)/(content)/profile/my-posts/[user-id]/page.tsx
app/(pages)/(content)/profile/page.tsx
components/post/post-buttons.tsx
components/post/post-sidebar.tsx
utils/footer-link.ts

Se agrego mas separacion entre tarjetas.

Scrum 310 mejorar post sidebar

---

components/pet-breeds.tsx

Camios para estilos similares al componente de animal y animal estatus

---

app/(pages)/(content)/add-post/page.tsx
app/(pages)/(content)/edit-post/[postId]/page.tsx
components/form/modal.tsx
types/post.ts
utils/posts.http.ts
validations/post-schema.ts

- Se cambia el orden de los inputs, el mapa queda al final del formulario.
- Se agrega zod para las validaciones para la página de crear y editar una publicación.
- Se crea el schema para el formulario de post.

Scrum313 bugfix post

---

app/(pages)/(content)/administration/settings/page.tsx
app/(pages)/(content)/pruebas/page.tsx
components/form-animal.tsx
components/form-pet-status.tsx
components/form/modal.tsx
components/modal.tsx
components/post/post-map.tsx
components/report-form.tsx
types/report.ts
utils/reports.http.ts
validations/animal-schema.ts
validations/pet-status-schema.ts
validations/report-schema.ts

Se uso hook form y zod para los mensajes de validacion debajo de los inputs y alert para los mensajes de la api (por ejemplo cuando se quiere crear un animal que ya existe)

Sc 321 fe estandarizar mensajes de error administracion

---

app/(pages)/(content)/pets/[id]/page.tsx
app/(pages)/(content)/posts/[id]/page.tsx
components/post/post-buttons.tsx
utils/posts.http.ts

Ahora la funcionalidad es asi:
Si el usuario esta logeado se aumenta el sharedCounter sino realiza solamente la copia de la url
**Cómo probar?**
- Se accede a un post dandole click a un post y tenga la url posts/[id].
- Haga click en el boton de compartir.
- Luego verifique en el swagger obteniendo el post por su id y vea su campo sharedCounter.

Scrum292 shared counter funcionality

---

app/(pages)/(content)/add-post/page.tsx
app/(pages)/(content)/edit-post/[postId]/page.tsx

**Descripción**
Se ha agregado el uso del Alert de Material Tailwind en acciones completadas. Tambien se a agregado un cambio que se ha sobreescrito, que arregla que el modal de confirmación de superponga con el mapa.
**Como probar?**
- Realizar un create, edit o delete de un post.
- Ver la alerta

Scrum335 add post alert

---

app/(pages)/(content)/administration/settings/page.tsx
components/admin-card/clickable-tag.tsx
components/card.tsx
components/form-report-reason.tsx
utils/report-reasons.http.ts
validations/report-reason-schema.ts

Se agrego el componente Report Reason en la seccion de configuracion de administracion para poder realizar crud con sus respectivas validaciones y alert

Sc 270 fe realizar formulario para crear/editar/eliminar report reasons

---

app/(pages)/(content)/dashboard/page.tsx
app/(pages)/(content)/profile/[id]/page.tsx
app/(pages)/(content)/profile/my-pets/[id]/page.tsx
app/(pages)/(content)/profile/my-posts/[id]/page.tsx
app/(pages)/(content)/profile/page.tsx
components/petCard/card-text.tsx
components/profile/detail-form.tsx
components/profile/dropdown-buttons.tsx
components/section.tsx
utils/user-client.ts

En este PR se crea la nueva pagina de ver perfil de otros usuarios
[S-318](https://projectliderfiuni2025.atlassian.net/browse/SCRUM-318?atlOrigin=eyJpIjoiOGJiZGY0YTczNWRiNDRmZGJhMzYyOTZhMGZhZDczNWYiLCJwIjoiaiJ9)
1. Implemente la pagina del perfil de otro usuario, con la ruta /profile/id
2. Refactorice componentes como cardText y section
3. Mejore estilos de la pagina profile y profile/id
4. Modifique el acceso para que si sos el usuario del perfil te aparezcan los botones de editar y sino los de contactar y reportar

S-318 Crear el perfil de otros usuarios

---

app/(pages)/(content)/profile/[id]/page.tsx

Solucione el problema de que no redirigia cuando entrabas a un perfil con /profile/mi-id a solo /profile

Resuelve el bug de que no redirige a profile cuando buscas tu perfil

---

app/(pages)/(content)/profile/[id]/page.tsx

Soluciona el bug de que no carga los datos del profile al no estar logeado

S 352 bug profile data

---

components/buttons/add-pet.tsx
components/petCard/pet-card.tsx
components/section.tsx
styles/globals.css

En este PR se crea el componente boton y se integra a mi perfil, no se muestra en el de los demas
> [!NOTE]
> El enlace dirige a missing, el que esta trabajando en esa pagina deberia cambiar la ubicacion

 Añadir el botón para crear mascota en el perfil

---

components/profile/dropdown-buttons.tsx

Este PR soluciona el bug que no se mostraban las opciones del boton de contactar

BUG - No aparece el boton de contactar en profile

---

app/(pages)/(content)/administration/report/[id]/page.tsx
app/(pages)/auth/login/page.tsx
app/(pages)/auth/register/page.tsx
components/admin-card/clickable-tag.tsx
components/administration/report/card-button.tsx
components/buttons/add-pet.tsx
components/buttons/edit-button.tsx
components/buttons/favorite-button.tsx
components/buttons/menu-button.tsx
components/buttons/report-button.tsx
components/buttons/send-button.tsx
components/buttons/trash-button.tsx
components/custom-select.tsx
components/modal.tsx
components/petCard/pet-card.tsx
components/petCard/tag.tsx
components/post/post-buttons.tsx
components/profile/detail-form.tsx
components/profile/dropdown-buttons.tsx
components/section.tsx
components/title.tsx
components/user-header.tsx
styles/globals.css

Reemplazar íconos de material con íconos de Lucide, actualiza estilos y tamaños para una mejor consistencia

S 221 Unificar la libreria de iconos

---

app/(pages)/(content)/administration/settings/page.tsx

se arreglo el delete para estado de mascota

fix delete pet status

---

components/buttons/edit-button.tsx

Se agrego que cuando le das a editar aparezca el icono de x en vez de editar

S 347 update edit button

---

components/comments/comment-item.tsx

…g minimum width to the comment container

S-350-Comentario-largo-no-aparece-completo

---

app/(pages)/auth/google-callback/page.tsx

[Ticket S-304](https://projectliderfiuni2025.atlassian.net/browse/SCRUM-304?atlOrigin=eyJpIjoiNmMyZjA2YTlhZTM0NGJiM2EzZDZhMzdmNmExZDE3YmQiLCJwIjoiaiJ9)

Implement error handling and alert display for Google login flow

---

app/(pages)/(content)/volunteering/page.tsx

Creación de la página para posts de tipo voluntariado sin filtros (eso se hará en otro ticket) y con un paginado limitado temporal (se mejorará cuando el back permita obtener la cantidad de páginas)
Se puede avanzar más allá de la página con posts, esto se arreglará cuando se cumpla lo anteriormente mencionado

S293 volunteering page

---

app/(pages)/(content)/profile/favorites/page.tsx
components/petCard/pet-card.tsx
components/post/post-buttons.tsx

Se corrige el problema de la redireccion de los favoritos.
Se añade que las publicaciones pets no tengan boton de favoritos.

Scrum 351 post en favoritos redirige a pagina no encontrada

---

components/post/post-header.tsx

Se agrego link que redirige al perfil de la persona que publico el post/pet

add link to profile

---

app/(pages)/(content)/posts/[id]/page.tsx
components/post/post-buttons.tsx

Se agregó el botón que redirige al formulario de publicación, permitiendo al usuario editar o eliminar aquellos posts de los cuales es propietario

add edit button

---

app/(pages)/(content)/add-post/page.tsx
app/(pages)/(content)/edit-post/[postId]/page.tsx
next.config.mjs
utils/media.http.ts

**Descripción**
Se realiza la funcionalidad de eliminar una imagen en la creación de un post y en un edit de un post, se agrega los limites de una imagen.
> [!CAUTION]
> Se modificó la configuración del archivo next.config.mjs
**Como probar?**
- Entrar en crear publicación o un edit de una publicacion.
- Agregar una foto, si es un edit probar eliminar y cargar otra imagen.
- Eliminar la imagen con la x .

Scrum 202 fe agregar funcionalidad de borrar cambiar una foto de una publicacion

---

app/(pages)/(content)/profile/page.tsx
app/(pages)/auth/create-profile/layout.tsx
app/(pages)/auth/create-profile/page.tsx
app/(pages)/auth/layout.tsx
app/(pages)/auth/login/page.tsx
components/profile/create-form.tsx
components/profile/welcome-user.tsx
contexts/auth-context.tsx
types/auth.ts
types/user-profile.ts
validations/user-profile.ts

Implementar  el formulario de registro de perfil, permitiendo a los usuarios seleccionar o confirmar su ubicación geográfica de manera visual.

S 291 complete profile registration

---

components/post/post-buttons.tsx

Botón de editar mis mascotas

---

validations/user-profile.ts

Agreegue acentos a las validaciones de direccion

Update address validation regex to allow accented characters

---

app/(pages)/(content)/adoption/page.tsx
utils/pets.http.ts

Arreglamos los errores que aparecieron al resetear los datos de la db. Ahora la page de adoption funciona de manera correcta.

Hot fix adoption

---

app/(pages)/(content)/dashboard/page.tsx
components/petCard/pet-card.tsx
components/section.tsx
styles/globals.css
tailwind.config.ts
types/title.ts

Se arregla el dashboard para que se muestre las publicaciones.

Hotfix dashboard

---

app/(pages)/(content)/missing/page.tsx
validations/pet-schema.ts

Los valores por defecto de los selects funcionan, los botones de crear y cancelar mascotas redirigen a sus páginas correspondientes como feedback, no permite crear la mascota si faltan los campos requeridos.

Git checkout  b scrum 334 mdejroa de fix refactorizar mensajes de error extraviados

---

app/(pages)/(content)/pets/[id]/page.tsx
components/post/post-buttons.tsx

se arreglaron los botones de editar post para que no aparezcan doble

Hot fix edit button

---

app/(pages)/(content)/profile/page.tsx
components/post/post-location-map.tsx
components/profile/detail-form.tsx
validations/user-profile.ts

Se debe ver y editar informacion nueva del usuario

S358 User profile

---

app/(pages)/(content)/edit-pets/[petId]/page.tsx
components/post/post-buttons.tsx
types/pet.ts
utils/pets.http.ts
validations/pet-schema.ts

Se puede acceder a la pagina de edición con el botón que se encuentra dentro de los detalles de las mascotas

Git checkout  b scrum 186 fe realizar formulario para editar y eliminar mascotas

---

app/(pages)/(content)/edit-pets/[petId]/page.tsx
app/(pages)/(content)/edit-post/[postId]/page.tsx
components/post/post-buttons.tsx

Se muestra el boton cuando el que esta viendo es el dueño del post/pet y redirige correctamente a los formularios de edicion correspondiente

Sc 370 bug arreglar boton de editar pet y post

---

app/(pages)/examples/pagination/page.tsx
components/pagination.tsx
hooks/use-pagination.ts
types/pagination.ts
utils/posts.http.ts

Se puede mirar el ejemplo en /examples/pagination
[Ticket S-373](https://projectliderfiuni2025.atlassian.net/browse/SCRUM-373?atlOrigin=eyJpIjoiMzAxYjBhZmY5MjcyNDgxNzgzNTY0ZTBlY2Y5NDNkYjciLCJwIjoiaiJ9)

S 373 paginacion reutilizable

---

app/(pages)/(content)/administration/report/[id]/page.tsx
components/administration/report/card-button.tsx

Correccion de errores de tipeo en reportes de publicaciones

Scrum 312 errores de tipeo

---

components/report-form.tsx
types/report.ts
utils/report-reasons.http.ts
utils/reports.http.ts
validations/report-schema.ts

---
Se actualizaron las rutas para reportar, el interface y schema para la funcionalidad de reportar tanto posts como pets

Sc 372 fe cambiar la llamada al boton de reportar al nuevo endpoint

---

app/(pages)/(content)/adoption/page.tsx
types/pet.ts

**Descripción**
- Se agrega la paginación utilizando el componente de paginación en la página de adopción.
- Se arregla que al filtrar por el tipo de animal no traia nada, ahora ya trae el tipo animal correspondiente.

ADOPTAMENA-409 fe paginación en la pantalla de adopción

---

app/(pages)/(content)/volunteering/page.tsx

Se ha utilizado el componente de paginación en la pantalla de voluntariado.

ADOPTAMENA-366 fe implementar paginación la pantalla de voluntariado

---

components/report-form.tsx

Se agrego mensaje de reporte enviado con exito al enviar un reporte
[ticket](https://projectliderfiuni2025.atlassian.net/browse/ADOPTAMENA-415?atlOrigin=eyJpIjoiNjMwNGY3NzBiN2FmNGVmN2EzN2VmNmI0MWQwMmEwYzEiLCJwIjoiaiJ9)

Feedback reporte

---

components/report-form.tsx

Muestra el mensaje al enviar reporte 
[ticket](https://projectliderfiuni2025.atlassian.net/browse/ADOPTAMENA-415?atlOrigin=eyJpIjoiYTUxYzFmZDBlM2ZkNGFhOTkzOThjOTRiMTJjMmJiMzYiLCJwIjoiaiJ9)

fix succes message

---

app/(pages)/(content)/profile/my-posts/[id]/page.tsx
types/pagination.ts
utils/posts.http.ts

- Se agrega el filtro por tipo de publicación en la pantalla de mis publicaciones.
- Se eliminó el filtro por animal ya que post no tiene relación con tipo de animal.

ADOPTAMENA-363 fe dar funcionalidad a los filtros de mis posts

---

app/(pages)/(content)/add-pet/page.tsx
app/(pages)/(content)/add-post/page.tsx
app/(pages)/(content)/edit-pets/[petId]/page.tsx
app/(pages)/(content)/edit-post/[postId]/page.tsx
types/pet.ts
types/tag.ts
utils/pet-statuses.http.ts
utils/pets.http.ts
validations/pet-schema.ts

Se modificó el create, edit y delete de pets de acuerdo a la nueva funcionalidad de la api de pets.

Adoptamena 419 fe arreglar bugs generales de pets

---

app/(pages)/(content)/volunteering/page.tsx
types/constants.ts
types/pagination.ts
utils/tags.ts

- Se agrega la funcionalidad de filtro por tags en la pantalla de voluntariado.
- El filtro se llama Tipo de ayuda

ADOPTAMENA-352 Se agrega a la pantalla de voluntariado el filtro por tags.

---

app/(pages)/(content)/administration/sponsors/page.tsx
app/(pages)/(content)/layout.tsx
app/(pages)/(content)/sponsors/create/page.tsx
components/sponsorsCarousel.tsx
types/sponsor.ts
utils/media.http.ts
utils/sponsor.http.ts
utils/user-client.ts
utils/user-profile-client.ts

**### Ajustes en el Formulario de Creación (app/(pages)/(content)/sponsors/create/page.tsx)**
Eliminación del campo "Nombre de la empresa" ya que este se maneja automáticamente según el tipo de usuario
Actualización de las validaciones según el backend:
Razón: máximo 255 caracteres (obligatorio)
Contacto: máximo 100 caracteres (obligatorio)
Logo: obligatorio
Nombre del responsable: máximo 100 caracteres
Actualización del tipo Sponsor para incluir todos los campos del backend:
Simplificación del tipo CreateSponsorRequest:
Mejoras en la Visualización de Sponsors (app/(pages)/(content)/administration/sponsors/page.tsx)
Implementación de lógica para mostrar el nombre correcto en las cards:
Muestra organizationName para usuarios tipo organización
Muestra fullName para usuarios normales …

Crear pantalla de administracion auspiciantes

---

app/(pages)/(content)/administration/sponsors/page.tsx
app/(pages)/(content)/layout.tsx
app/(pages)/(content)/sponsors/create/page.tsx
components/sponsorsCarousel.tsx
types/sponsor.ts
utils/media.http.ts
utils/sponsor.http.ts
utils/user-profile-client.ts

Reverts sebasbogado/AdoptameNa-Frontend#211

Revert "Revert "Crear pantalla de administracion auspiciantes""

---

app/(pages)/(content)/add-product/page.tsx
app/(pages)/(content)/marketplace/page.tsx
components/multi-select.tsx
types/product-condition.ts
types/product.ts
utils/product.http.ts
utils/user-profile-client.ts
validations/product-schema.ts

- se agrego el formulario para crear productos en /add-product
- se puede acceder mediante el boton de + en /marketplace

Adoptamena 399 fe formulario para crear publicacion de marketplace

---

app/(pages)/(content)/add-pet/page.tsx
app/(pages)/(content)/add-post/page.tsx
app/(pages)/(content)/edit-pets/[petId]/page.tsx
app/(pages)/(content)/edit-post/[postId]/page.tsx

Se redujo los tiempos de respuesta de los formularios

Adoptamena 360 bug reducir tiempo de espera luego de confirmar crear post y pet

---

app/(pages)/(content)/add-product/page.tsx

Luego de crear se redirecciona a marketplace

fix router to marketplace

---

utils/user-profile-client.ts

Fix de llamada al api en utils/user-profile-client.ts

Arreglado put axios de updateUserProfile

---

app/(pages)/(content)/adoption/page.tsx
app/(pages)/(content)/blog/page.tsx
app/(pages)/(content)/marketplace/page.tsx
app/(pages)/(content)/missing/page.tsx
app/(pages)/(content)/profile/my-pets/[id]/page.tsx
app/(pages)/(content)/profile/my-posts/[id]/page.tsx
app/(pages)/(content)/volunteering/page.tsx

- Se modifico el tamaño de page a 20 en todas la páginas(voluntariado, adopcion, blog, extraviado, marketplace, my-post, my-pets).
- Se estantarizo como se muestran las publicaciones en todas las pantallas(voluntariado, adopcion, blog, extraviado, marketplace, my-post, my-pets).

Estandarizacion en el listado de publicaciones y page size

---

app/(pages)/(content)/add-pet/page.tsx
app/(pages)/(content)/dashboard/page.tsx
app/(pages)/(content)/marketplace/page.tsx

PR anterior fue incorrectamente a Main.
Se mantiene ese merge, pero tambien se actualizan los cambios en dev

Arreglar errores Gramaticales

---

app/(pages)/(content)/dashboard/page.tsx
components/petCard/card-image.tsx
components/petCard/card-text.tsx
components/petCard/missing-tags.tsx
components/petCard/pet-card.tsx
components/petCard/tag.tsx
components/product-Card/product-card.tsx
components/section.tsx
components/title.tsx
styles/globals.css

Refactorizar para hacer responsive la pagina del dashboard, solo el page, no incluye banner ni nav, ni otros elementos
- Edite los estilos utilizando los breakpoints de tailwind
- Apliqué el principio de mobile first
- Cambie tamaños del texto para cada tamaño de pantalla
- Cambie tamaños del card y tags

Adoptamena 466 fe hacer responsive el dashboard

---

components/post/post-header.tsx

Agregué quién publicó una mascota a los detalles de la mascota, anteriormente esto se mostraba solo en posts

SC-460-show-pet-owner

---

components/profile/detail-form.tsx
styles/globals.css
tailwind.config.ts

Cambié el tamaño de las fuentes de los detalles del perfil, ademas hice que el campo y los íconos de teléfono y dirección se oculten cuando esos datos no están disponibles ya que actualmente se muestran los íconos pero sin el valor
Además agregué los colores de texto del figma ya que actualmente se está usando negro 100% y el diseño es con negro tintado.

SC-443-profile-details-redesign

---

app/(pages)/(content)/sponsors/create/page.tsx
components/banner/banner-image.tsx
types/sponsor.ts
utils/file-schema.ts

Implementación de subir solicitud de banner para auspiciantes

implementacion de subir banner

---

app/(pages)/(content)/profile/layout.tsx
app/(pages)/(content)/profile/received-request/page.tsx

Página inicial para gestionar las solicitudes de Auspicio y adopción

modificación de la página de solicitudes

---

components/buttons/report-button.tsx
components/post/post-buttons.tsx
components/post/post-comments.tsx
components/report-form.tsx
types/report.ts
validations/report-schema.ts

Funcionalidad del boton reportar comentario
[ticket](https://projectliderfiuni2025.atlassian.net/browse/ADOPTAMENA-486?atlOrigin=eyJpIjoiMDI4MWNjZGMzOGYwNGEzYmFhOTM3N2QzNjM4NjE0MmQiLCJwIjoiaiJ9)

Adoptamena 486 fe funcionalidad de reportar un comentario

---

app/(pages)/(content)/add-pet/page.tsx
app/(pages)/(content)/add-post/page.tsx
app/(pages)/(content)/add-product/page.tsx
app/(pages)/(content)/dashboard/page.tsx
app/(pages)/(content)/marketplace/page.tsx
app/(pages)/(content)/profile/[id]/page.tsx
app/(pages)/(content)/profile/page.tsx
components/inputs/labeled-input.tsx
components/multi-select.tsx

Realicé correcciones generales al CSS de distintas páginas, ver detalle en el ticket: https://projectliderfiuni2025.atlassian.net/browse/ADOPTAMENA-497
Cada cambio está ecplicado en su correpondiente commit

SC 497 CSS General Fixes

---

app/(pages)/(content)/add-post/page.tsx
app/(pages)/(content)/edit-post/[postId]/page.tsx

Se agrega el limite a 5 tags a una creación o edición de publicación.

Se agrega el limite de tags al crear y editar publicación

---

app/(pages)/(content)/edit-product/[productId]/page.tsx
components/product/product-header.tsx
types/product.ts
utils/product.http.ts
validations/product-schema.ts

- Se agregó la reedirección del boton editar producto a la página de editar.
- Se realizó el formulario de editar producto.
- Se realiza la funcionalidad de editar un producto.
- Se realiza la funcionalidad de eliminar un producto.

Adoptamena 495 fe funcionalidad boton editar producto

---

app/(pages)/(content)/add-product/page.tsx

- Se agregó la validación faltante de formatos válidos para la subida de imagenes en crear producto.

ADOPTAMENA-493 bug alerta en crear producto

---

components/buttons/report-button.tsx
components/product/product-header.tsx
components/report-form.tsx
validations/report-schema.ts

Funcionalidad de reportar producto mediante el report button
[ticket](https://projectliderfiuni2025.atlassian.net/browse/ADOPTAMENA-494?atlOrigin=eyJpIjoiMzk5YWEwMzA5ODZhNGZjZWJmOWRmMmRjNGJkODNmYWYiLCJwIjoiaiJ9)

ADOPTAMENA-494-fe-funcionalidad-reportar-producto

---

app/(pages)/(content)/dashboard/page.tsx
components/petCard/card-text.tsx
components/petCard/tag.tsx

- Se modifica para que los tags de las publicaciones de post muestren de forma correcta.
- Cambio en los estilos de los tags ya que no estan implementadas correctamente.

fix: update pet status handling and improve tag rendering logic

---

app/(pages)/(content)/edit-pets/[petId]/page.tsx
app/(pages)/(content)/edit-post/[postId]/page.tsx
components/post/post-buttons.tsx

- Se modificó el delete post y pet para que no borre las imagenes relacionadas a estas.
- Se arregló un fallo al realizar click en un edit de un pet y post, que al realizar click al boton de editar un post mostraba las opciones incorrectas.

Fix edit button and delete post pet

---

app/(pages)/(content)/profile/notifications/page.tsx
app/layout.tsx
components/comments/comment-item.tsx
components/notification-bell.tsx
components/user-header.tsx
contexts/notification-context.tsx
package-lock.json
package.json
types/notification.ts
types/pagination.ts
utils/date-format.ts
utils/notifications.http.ts

Se muestran las notifiaciones en tiempo real y tambien en su page

S 464 Implementar notificaciones

---

app/(pages)/(content)/profile/notifications/page.tsx
components/notification-bell.tsx
contexts/notification-context.tsx
hooks/notification-hooks.ts
hooks/websocket-hook.ts
middleware.ts
utils/notification-state.ts
utils/notification-websocket.ts

Refactor WebSocket logic into separate module

---

app/(pages)/(content)/marketplace/page.tsx
components/filters/location-filter.tsx

- Se ha agregado el filtro por ubicación utilizando componentes existentes.

ADOPTAMENA-534 fe filtrar por ubicacion marketplace

---

app/(pages)/(content)/profile/[id]/page.tsx
app/(pages)/(content)/profile/page.tsx

Agregue en mi perfil y el perfil de otros usuarios la seccion de los productos publicados por el usuario
**Link del ticket de jira**: [S-517](https://projectliderfiuni2025.atlassian.net/browse/ADOPTAMENA-517?atlOrigin=eyJpIjoiNDEwYzI4ZGQxYmE0NGIzZDg1MTYxMmQ3ZDljNTJjZDIiLCJwIjoiaiJ9)
- Los cambios se encuentran en la ruta /profile y /profile/id
- Verificar que los productos correspondan a la id del usuario actual

Adoptamena 517 fe implementar mis productos publicados

---

components/petCard/card-text.tsx

Referencia: https://www.figma.com/design/25JYkMPSMjS2bcUumHH8bv/Adoptamena?node-id=324-13731&t=jTUi68UpHOKZpv32-4 
Agregué campo de autor del post y una barra de progreso y el total a recaudar del crowdfunding, se debe pasar al componente el monto total y el actual y realiza al cálculo
Para testear el campo de recaudación enviarle a cardText un valor para el monto total y actual dentro del componente PetCard: totalAmount={15000000} currentAmount={1000000}

Sc 562 add attributes to pet card

---

components/product/product-image-carousel.tsx

- Se ha realizado la funcionalidad de al realizar click en la miniatura de las fotos, se mueva el carrousel a la imagen clickeada.
Probar en marketplace/[id]

ADOPTAMENA-548 fe mejora click en la previsualizacion de imagenes en detalle de producto

---

app/(pages)/(content)/blog/page.tsx
app/(pages)/(content)/profile/favorites/page.tsx
components/blog/blog-card.tsx
components/petCard/card-image.tsx
utils/date-format.ts
utils/text/clean-markdown.ts

Cree un nuevo componente blog card, y lo hice responsive. 
**Link del ticket de jira**[S-506](https://projectliderfiuni2025.atlassian.net/browse/ADOPTAMENA-506?atlOrigin=eyJpIjoiNmIzOWI1OGY3MzE2NDQ0Mjg2OTdmYjU1MDIyNWVkNTMiLCJwIjoiaiJ9)
Los cards se pueden visualizar en la seccion de blog. En el dashboard deje los cards normales
> [!IMPORTANT]
> Tenia los cambios en otra rama y mergee a esta. Cuando se apruebe esta rama, borrare la otra

Adoptamena 506 fe crear componente blog card

---

app/(pages)/(content)/crowdfunding/page.tsx
app/(pages)/(content)/layout.tsx
components/crowdfundingCard/card-text.tsx
components/crowdfundingCard/crowdfunding-card.tsx
components/crowdfundingCard/tag.tsx
components/navbar.tsx
components/petCard/card-image.tsx
types/crowfunding-type.ts
types/pagination.ts
utils/crowfunding.http.ts

- Se ha realizado una nueva sección en el navbar Colecta
- Se ha realizado la pagina crowdfunding donde lista todas la colectas activas
- Al realizar un click en el card se reedirige a la cuenta de la organización del quien creó la colecta
- Se ha creado un nuevo componente card para crowdfunding reutilizando lo necesario de pet card
- Se ha creado un nuevo componente CrowdfundingCardText para soportar metas
- Se ha creado un nuevo componente tag(se puede utilizar el que ya existe pero que soporte todos los tipos de publicación ya sea post, pet, product, crowdfunding)
Diseño del card crowdfunding final:
**Nueva modificación**
- Se ha modificado card image para que muestre un loader mientras carga la imagen, esta modificación se aplica para todos los cards

ADOPTAMENA-561 fe implementar seccion de colecta

---

app/(pages)/(content)/add-pet/page.tsx
app/(pages)/(content)/add-product/page.tsx
app/(pages)/(content)/edit-pets/[petId]/page.tsx
app/(pages)/(content)/edit-post/[postId]/page.tsx
app/(pages)/(content)/edit-product/[productId]/page.tsx
components/newBanner.tsx

La página add-pet tenía un botón para ver la imagen en pantalla completa pero toda la lógica estaba en la página en lugar del componente y add-pet era la única página con esta funcionalidad. 
El bug era que se veía en la parte de arriba en vez de estar centrado pero me pareció que además debía estar en todas las página que usen el componente newBanner y no solo en una, agregué la funcionalidad de fullscreen dentro del componente NewBanner y actualicé las páginas que lo usaban para que todas se vean iguales.
Para testear este ticket asegurarse de que se pueden crear post, pets y products correctamente tras el cambio y que las imágenes se suben correctamente

SC-558-fix-fullScreen-bug

---

cypress/e2e/banner.cy.ts
cypress/e2e/login.cy.ts
cypress/e2e/logout.cy.ts
cypress/e2e/profile.cy.ts
cypress/e2e/register-org.cy.ts
cypress/e2e/register.cy.ts
cypress/e2e/setting.cy.ts
cypress/e2e/sponsor.cy.ts
cypress/e2e/user.cy.ts

Adición de nuevos tests automatizados y modificación de tests anteriores

Tests Automatizados con Cypress

---

contexts/favorites-context.tsx

esto es solo temporal para poder seguir trabajando

Hotfix favorites 

---

app/(pages)/(content)/profile/[id]/page.tsx
app/(pages)/(content)/profile/my-products/[id]/page.tsx
app/(pages)/(content)/profile/page.tsx
components/inputs/labeled-input.tsx
components/labeled-selected.tsx

Cree una nueva pagina de mis productos con todos los filtros necesarios 
Se puede probar entrando en un perfil y dandole a su seccion sus productos
La pagina esta en /profile/my-products/id-user

Adoptamena 577 fe implementar pagina de my products

---

app/(pages)/(content)/add-pet/page.tsx
app/(pages)/(content)/edit-pets/[petId]/page.tsx
components/navbar.tsx
styles/globals.css
tailwind.config.ts

Modifique add/edit pet de acuerdo a disenho en figma

SC-511-Refactor-Pets-Forms

---

components/petCard/card-text.tsx
components/post/post-header.tsx
components/product/product-header.tsx
types/pet.ts
types/post.ts
types/product.ts

Agregado organization name al detalle del post, se muestra si tiene, si no, se muestra el nombre del usuario

Sc 582 show organization name

---

app/(pages)/(content)/adoption/page.tsx
app/(pages)/(content)/blog/page.tsx
app/(pages)/(content)/dashboard/page.tsx
app/(pages)/(content)/marketplace/page.tsx
app/(pages)/(content)/missing/page.tsx
app/(pages)/(content)/volunteering/page.tsx
components/buttons/create-publication-buttons.tsx

- Se ha creado un componente para los botones para acceder a la creación de publicaciones.
- En el dashboard aparece todas las opciones de crear post, pet y product, pero al acceder a una sección aparece solamente la opción correspondiente. Ej: en la sección de marketplace solamente aparecerá la opción de Añadir Producto.
Preview del componente:
Estado del componente en la sección de marketplace:

Adoptamena 564 fe agregar select al boton de crear publicacion que rediriga al formulario correspondiente

---

components/petCard/card-text.tsx

Adición del precio a los productCard

Adición del precio en los productcard

---

app/(pages)/(content)/profile/report/page.tsx
app/(pages)/(content)/profile/report/products/[id]/page.tsx
app/(pages)/(content)/profile/report/products/page.tsx
components/profile/report/user-report-card-button.tsx
components/profile/report/user-report-detail.tsx
components/profile/report/user-report-list-page.tsx

Enlace en local: http://localhost:3000/profile/report/products
Se muestran los productos reportados por el usuario y permite ingresar a cada ver cual fue la razón del reporte junto con la fecha.

S515 my report products

---

components/post/post-buttons.tsx

Hide report button when editing a post in PostButtons component

---

app/(pages)/(content)/chats/page.tsx
components/chat/chat-input.tsx
components/chat/chat-message.tsx
components/chat/chat-user-list-item.tsx

- Added search functionality to filter chat users by name in ChatsPage.
- Updated ChatInput component to ensure full width and improved styling.
- Enhanced ChatMessage component to handle overflow and improved text display.
- Adjusted ChatUserListItem for better layout and responsiveness.

Enhance chat functionality with search and improved UI elements

---

app/(pages)/(content)/add-pet/page.tsx
app/(pages)/(content)/edit-pets/[petId]/page.tsx

Se agrega el mensaje de validación al no ingresar una ubicación en el mapa.

Adoptamena-595 BUG Add error message display for address coordinates in pet form

---

app/(pages)/(content)/edit-post/[postId]/page.tsx

Tipos de archivos permitidos:
Imágenes:
JPEG/JPG (.jpg, .jpeg)
PNG (.png)
WEBP (.webp)
Videos:
MP4 (.mp4)
WEBM (.webm)
OGG (.ogg)
MKV (.mkv) - video/x-matroska
Audio:
MP3 (.mp3) - audio/mpeg
Actualizado el atributo accept del input para incluir todos los tipos permitidos
Modificado la validación de tamaño:
Imágenes: 5MB
Videos y Audio: 50MB
Agregado soporte para archivos de audio en la validación de tamaño
Actualizado el mensaje de error para mostrar todos los formatos permitidos

correccion del bug

---

components/product/product-image-carousel.tsx

Faltó el soporte para videos en el carrusel de productos

Agregue soporte para videos en el carousel de products

---

app/(pages)/(content)/profile/[id]/page.tsx
app/(pages)/(content)/profile/layout.tsx
app/(pages)/(content)/profile/page.tsx
types/crowfunding-type.ts

En app/(pages)/(content)/profile/[id]/page.tsx, modifique el useEffect para que solo redirija al login cuando el usuario está viendo su propio perfil.
En app/(pages)/(content)/profile/layout.tsx, modifique el useEffect para que solo redirija al login cuando el usuario está en la ruta /profile (su propio perfil).
En app/(pages)/(content)/profile/page.tsx, mantuve la redirección al login ya que esta es la página del perfil propio del usuario.

correccion del error de perfiles

---

components/profile/report/user-report-card-button.tsx
components/profile/report/user-report-list-page.tsx

Cambio de título de sección y uso de productCard

Cambio de título de sección y uso de productCard

---

components/navbar-admin.tsx

Se agregó un dropdown en la pantalla de administración para el ítem de usuario, que contiene los regulares, organizadores y administradores

adoptamena 550 fe agregar dropdown en navbar admin para que se listen por usuario organizacion y administrador

---

app/(pages)/(content)/adoption/page.tsx

Aplicar CapitalizeFirstLetter en el filtro Animal en la pagina adoption

FIX-CapitalizeFirstLetter en Animal - 546

---

components/blog/blog-card.tsx
components/petCard/card-text.tsx
components/petCard/tag.tsx
utils/Utils.ts

- Se muestra dinamicamente los tags en los cards.

ADOPTAMENA-598 Modificar tags en cards

---

components/petCard/card-text.tsx
components/petCard/tag.tsx
utils/Utils.ts

Aceptar el https://github.com/sebasbogado/AdoptameNa-Frontend/pull/365 primero

Adoptamena modificar color tag macho hembra

---

components/footer.tsx

- Se realiza responsive al footer.
- Se agrega el copyright y un boton de ir al inicio.

Adoptamena 621 fe hacer responsive footer

---

app/(pages)/(content)/administration/crowfunding/page.tsx
app/(pages)/(content)/administration/layout.tsx
app/(pages)/(content)/administration/sponsors/page.tsx
app/(pages)/(content)/terms-and-conditions/page.tsx
components/request/request-card.tsx

1. Administración de Colectas (administration/crowfunding/page.tsx y RequestCard)
Eliminación de solicitudes:
Ahora puedes eliminar cualquier solicitud que no esté en estado "ACTIVE" o "PENDING". El flujo de eliminación es directo: el modal de confirmación está en el card y la petición al backend se ejecuta inmediatamente al confirmar.
Eliminación de alertas duplicadas:
Los mensajes de éxito/error ahora se gestionan solo desde el card, no desde la página.
Visualización de la foto de perfil:
El card ahora muestra la foto de perfil del usuario solicitante, obtenida mediante la función getUserProfile y usando la propiedad media del perfil.
En ciertas páginas eliminé imports no utilizados

Adoptamena 625 fe utilizar componente request card

---

app/(pages)/(content)/marketplace/[id]/page.tsx
app/layout.tsx
components/comments/comments.tsx
components/post/post-location-map.tsx
components/product/product-detail.tsx
components/product/product-header.tsx
components/product/product-image-carousel.tsx
components/product/product-sidebar.tsx
components/product/product-specification.tsx

Hice responsive la página de detalles de un producto agregando tailwind breakpoints en los componentes para que se ajusten al tamaño de pantallas pequeñas
Para testear verificar que toda la info se vea bien en mobile y que no se hayan roto los estilos en desktop

Sc 618 product detail responsiveness

---

app/(pages)/(content)/blog/page.tsx
components/ui/skeleton-blog-card.tsx

Cree el componente skeleton para el card de blog y agregue los skeleton loaders para filters y cards
⚠️ Este ticket requiere que https://projectliderfiuni2025.atlassian.net/browse/ADOPTAMENA-637 este mergeado a dev para funcionar ya que depende de un componente creado alli

SC-639-Add skeleton loader blog

---

app/(pages)/(content)/missing/page.tsx

Agregue el skeleton loader para cards y filters en la pagina de extraviados
⚠️ Este ticket requiere que https://projectliderfiuni2025.atlassian.net/browse/ADOPTAMENA-637 este mergeado a dev para funcionar ya que depende de un componente creado alli

Agregados skeleton loader para cards y filters

---

app/(pages)/(content)/crowdfunding/page.tsx
components/section.tsx

Agregue el skeleton loader a los cards de crowdfunding, ademas hice responsive el skeleton en el dashboard
Antes
Ahora

SC-641-Add-skeleton-loader-crowdfunding

---

app/(pages)/(content)/add-post/page.tsx
app/(pages)/(content)/edit-post/[postId]/page.tsx
components/form/modal.tsx

Corregido bug donde el modal de vonfirmacion se mostraba por debajo del footer

Sc 644 fix bug modal

---

app/(pages)/(content)/add-pet/page.tsx
app/(pages)/(content)/add-post/page.tsx
app/(pages)/(content)/edit-pets/[petId]/page.tsx
app/(pages)/(content)/edit-post/[postId]/page.tsx
components/post/form-data.tsx
types/pet.ts
types/post.ts
validations/pet-schema.ts
validations/post-schema.ts

> [!IMPORTANT]  
> Aceptar el pr: https://github.com/sebasbogado/AdoptameNa-Frontend/pull/419 primero
- Se agrega el checkbox al formulario de crear, editar de pets, post y blogs.
- Este ticket arregla los problemas de creación y edición de todos los formularios, osea que se debe revisar primero el pr 419 y seguidamente este. IMPORTANTE
Imagen del checkbox:

Adoptamena 611 fe agregar checkbox de imagen sensible en los formularios

---

app/(pages)/(content)/add-product/page.tsx
app/(pages)/(content)/edit-product/[productId]/page.tsx
validations/product-schema.ts

se agrego validacion para subir al menos una imagen en los formularios de productos

Adoptamena 635 bug agregar validacion en product

---

app/(pages)/(content)/administration/banned-posts/pets-publications/page.tsx
app/(pages)/(content)/administration/banned-posts/posts-publications/page.tsx
app/(pages)/(content)/administration/banned-posts/products-publications/page.tsx
app/(pages)/(content)/administration/page.tsx
app/(pages)/(content)/administration/report/comments/page.tsx
app/(pages)/(content)/administration/report/page.tsx
app/(pages)/(content)/administration/report/pets/page.tsx
app/(pages)/(content)/administration/report/posts/page.tsx
app/(pages)/(content)/administration/report/products/page.tsx
app/(pages)/(content)/administration/users/page.tsx
app/(pages)/(content)/profile/received-request/crowdfunding-sent/page.tsx
components/administration/estatistics/graph/bar.tsx
components/buttons/back-button.tsx
components/request/request-card.tsx

Modifique los datos que se muestran en solicitudes de administracion y tambien hice que vuelva a aparecer el logo de adoptamena cuendo es mis solicitudes
> [!IMPORTANT]
> Tambien modifique lo de que aparezca cantidad en vez de value en el grafico 
> Tambien agregue back buttons y unifique al estilo de la pagina

Refactor crowdfunding card

---

app/(pages)/(content)/crowdfunding/page.tsx
app/(pages)/(content)/dashboard/page.tsx
components/petCard/tag.tsx
components/section.tsx
styles/globals.css
tailwind.config.ts
types/title.ts

- Implemented crowdfunding data fetching in the dashboard page.
- Updated Section component to support crowdfunding items.
- Adjusted styles for crowdfunding in globals.css and tailwind.config.ts.
- Added crowdfunding colors to title.ts.

HOTFIX - Agregar sección de colecta en dashboard
